version: '3.3'

services:
  datos_postgres:
    image: "postgres:10-alpine"
    network_mode: host
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sample
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
